services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.postgres
    volumes:
      - dahsBoardDB:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
    command: >
      sh -c "python manage.py wait_for_db && \
        python manage.py makemigrations && \
        python manage.py migrate && \
        python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.backend

volumes:
  dahsBoardDB: