# Generated by Django 5.2 on 2025-04-21 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('bom_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bom_name', models.CharField(max_length=255)),
                ('produce_quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineMaster',
            fields=[
                ('name_of_machine', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('machine_process_name', models.CharField(max_length=500)),
                ('mould', models.CharField(max_length=255)),
                ('machine_capacity', models.FloatField()),
                ('machine_final_produce_product_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('product_item_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('opening_stock', models.FloatField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BOMItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='app.bom')),
            ],
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app.partymaster')),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('product_qty', models.FloatField()),
                ('machine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.machinemaster')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productmaster')),
            ],
        ),
    ]
