# Generated by Django 5.2 on 2025-04-26 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_machinemaster_mould'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machinemaster',
            name='name_of_machine',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
