# Generated by Django 5.2 on 2025-04-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bom_date_alter_machinemaster_name_of_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
