# Generated by Django 5.2 on 2025-05-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jobcard_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='operator_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='shift',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], default='DAY', max_length=10),
        ),
        migrations.AlterField(
            model_name='partyaddress',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app.partymaster'),
        ),
    ]
